/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDriversRouteImport } from './routes/_app/drivers'
import { Route as AppExceptionsRouteImport } from './routes/_app/exceptions'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppSettlementsRouteImport } from './routes/_app/settlements'
import { Route as AppStyleguideRouteImport } from './routes/_app/styleguide'
import { Route as AppWeekRouteImport } from './routes/_app/week'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthDevRouteImport } from './routes/auth/dev'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as PayrollExportRunIdRouteImport } from './routes/payroll-export.$runId'
import { Route as AppExtraJobsIndexRouteImport } from './routes/_app/extra-jobs/index'
import { Route as AppExtraJobsNewRouteImport } from './routes/_app/extra-jobs/new'
import { Route as AppHovershipIndexRouteImport } from './routes/_app/hovership/index'
import { Route as AppPayrollIndexRouteImport } from './routes/_app/payroll/index'
import { Route as AppPayrollRunIdRouteImport } from './routes/_app/payroll/$runId'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppSettingsRatesRouteImport } from './routes/_app/settings/rates'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as AppTforceTodayRouteImport } from './routes/_app/tforce/today'
import { Route as ApiIntegrationsDailyChangesRouteImport } from './routes/api/integrations/daily-changes'
import { Route as ApiIntegrationsExtraJobDraftsRouteImport } from './routes/api/integrations/extra-job-drafts'
import { Route as ApiIntegrationsImportsRouteImport } from './routes/api/integrations/imports'
import { Route as ApiIntegrationsMessagesRouteImport } from './routes/api/integrations/messages'
import { Route as ApiIntegrationsMorningListRouteImport } from './routes/api/integrations/morning-list'
import { Route as AppHovershipWeekWeekIdRouteImport } from './routes/_app/hovership/week/$weekId'
import { Route as AppTforceWeekIndexRouteImport } from './routes/_app/tforce/week/index'
import { Route as AppTforceWeekWeekIdRouteImport } from './routes/_app/tforce/week/$weekId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppExceptionsRoute = AppExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettlementsRoute = AppSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => AppRoute,
} as any)
const AppStyleguideRoute = AppStyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekRoute = AppWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDevRoute = AuthDevRouteImport.update({
  id: '/auth/dev',
  path: '/auth/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollExportRunIdRoute = PayrollExportRunIdRouteImport.update({
  id: '/payroll-export/$runId',
  path: '/payroll-export/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExtraJobsIndexRoute = AppExtraJobsIndexRouteImport.update({
  id: '/extra-jobs/',
  path: '/extra-jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppExtraJobsNewRoute = AppExtraJobsNewRouteImport.update({
  id: '/extra-jobs/new',
  path: '/extra-jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppHovershipIndexRoute = AppHovershipIndexRouteImport.update({
  id: '/hovership/',
  path: '/hovership/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRunIdRoute = AppPayrollRunIdRouteImport.update({
  id: '/payroll/$runId',
  path: '/payroll/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRatesRoute = AppSettingsRatesRouteImport.update({
  id: '/settings/rates',
  path: '/settings/rates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTforceTodayRoute = AppTforceTodayRouteImport.update({
  id: '/tforce/today',
  path: '/tforce/today',
  getParentRoute: () => AppRoute,
} as any)
const ApiIntegrationsDailyChangesRoute =
  ApiIntegrationsDailyChangesRouteImport.update({
    id: '/api/integrations/daily-changes',
    path: '/api/integrations/daily-changes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsExtraJobDraftsRoute =
  ApiIntegrationsExtraJobDraftsRouteImport.update({
    id: '/api/integrations/extra-job-drafts',
    path: '/api/integrations/extra-job-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsImportsRoute = ApiIntegrationsImportsRouteImport.update({
  id: '/api/integrations/imports',
  path: '/api/integrations/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsMessagesRoute = ApiIntegrationsMessagesRouteImport.update({
  id: '/api/integrations/messages',
  path: '/api/integrations/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsMorningListRoute =
  ApiIntegrationsMorningListRouteImport.update({
    id: '/api/integrations/morning-list',
    path: '/api/integrations/morning-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppHovershipWeekWeekIdRoute = AppHovershipWeekWeekIdRouteImport.update({
  id: '/hovership/week/$weekId',
  path: '/hovership/week/$weekId',
  getParentRoute: () => AppRoute,
} as any)
const AppTforceWeekIndexRoute = AppTforceWeekIndexRouteImport.update({
  id: '/tforce/week/',
  path: '/tforce/week/',
  getParentRoute: () => AppRoute,
} as any)
const AppTforceWeekWeekIdRoute = AppTforceWeekWeekIdRouteImport.update({
  id: '/tforce/week/$weekId',
  path: '/tforce/week/$weekId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/drivers': typeof AppDriversRoute
  '/exceptions': typeof AppExceptionsRoute
  '/services': typeof AppServicesRoute
  '/settlements': typeof AppSettlementsRoute
  '/styleguide': typeof AppStyleguideRoute
  '/week': typeof AppWeekRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/dev': typeof AuthDevRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/payroll-export/$runId': typeof PayrollExportRunIdRoute
  '/extra-jobs/new': typeof AppExtraJobsNewRoute
  '/payroll/$runId': typeof AppPayrollRunIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/rates': typeof AppSettingsRatesRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/tforce/today': typeof AppTforceTodayRoute
  '/api/integrations/daily-changes': typeof ApiIntegrationsDailyChangesRoute
  '/api/integrations/extra-job-drafts': typeof ApiIntegrationsExtraJobDraftsRoute
  '/api/integrations/imports': typeof ApiIntegrationsImportsRoute
  '/api/integrations/messages': typeof ApiIntegrationsMessagesRoute
  '/api/integrations/morning-list': typeof ApiIntegrationsMorningListRoute
  '/extra-jobs/': typeof AppExtraJobsIndexRoute
  '/hovership/': typeof AppHovershipIndexRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/hovership/week/$weekId': typeof AppHovershipWeekWeekIdRoute
  '/tforce/week/$weekId': typeof AppTforceWeekWeekIdRoute
  '/tforce/week/': typeof AppTforceWeekIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/drivers': typeof AppDriversRoute
  '/exceptions': typeof AppExceptionsRoute
  '/services': typeof AppServicesRoute
  '/settlements': typeof AppSettlementsRoute
  '/styleguide': typeof AppStyleguideRoute
  '/week': typeof AppWeekRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/dev': typeof AuthDevRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/payroll-export/$runId': typeof PayrollExportRunIdRoute
  '/': typeof AppIndexRoute
  '/extra-jobs/new': typeof AppExtraJobsNewRoute
  '/payroll/$runId': typeof AppPayrollRunIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/rates': typeof AppSettingsRatesRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/tforce/today': typeof AppTforceTodayRoute
  '/api/integrations/daily-changes': typeof ApiIntegrationsDailyChangesRoute
  '/api/integrations/extra-job-drafts': typeof ApiIntegrationsExtraJobDraftsRoute
  '/api/integrations/imports': typeof ApiIntegrationsImportsRoute
  '/api/integrations/messages': typeof ApiIntegrationsMessagesRoute
  '/api/integrations/morning-list': typeof ApiIntegrationsMorningListRoute
  '/extra-jobs': typeof AppExtraJobsIndexRoute
  '/hovership': typeof AppHovershipIndexRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/hovership/week/$weekId': typeof AppHovershipWeekWeekIdRoute
  '/tforce/week/$weekId': typeof AppTforceWeekWeekIdRoute
  '/tforce/week': typeof AppTforceWeekIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/drivers': typeof AppDriversRoute
  '/_app/exceptions': typeof AppExceptionsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settlements': typeof AppSettlementsRoute
  '/_app/styleguide': typeof AppStyleguideRoute
  '/_app/week': typeof AppWeekRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/dev': typeof AuthDevRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/payroll-export/$runId': typeof PayrollExportRunIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/extra-jobs/new': typeof AppExtraJobsNewRoute
  '/_app/payroll/$runId': typeof AppPayrollRunIdRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/rates': typeof AppSettingsRatesRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/tforce/today': typeof AppTforceTodayRoute
  '/api/integrations/daily-changes': typeof ApiIntegrationsDailyChangesRoute
  '/api/integrations/extra-job-drafts': typeof ApiIntegrationsExtraJobDraftsRoute
  '/api/integrations/imports': typeof ApiIntegrationsImportsRoute
  '/api/integrations/messages': typeof ApiIntegrationsMessagesRoute
  '/api/integrations/morning-list': typeof ApiIntegrationsMorningListRoute
  '/_app/extra-jobs/': typeof AppExtraJobsIndexRoute
  '/_app/hovership/': typeof AppHovershipIndexRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/hovership/week/$weekId': typeof AppHovershipWeekWeekIdRoute
  '/_app/tforce/week/$weekId': typeof AppTforceWeekWeekIdRoute
  '/_app/tforce/week/': typeof AppTforceWeekIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/drivers'
    | '/exceptions'
    | '/services'
    | '/settlements'
    | '/styleguide'
    | '/week'
    | '/auth/callback'
    | '/auth/dev'
    | '/auth/login'
    | '/auth/logout'
    | '/payroll-export/$runId'
    | '/extra-jobs/new'
    | '/payroll/$runId'
    | '/settings/audit'
    | '/settings/rates'
    | '/settings/team'
    | '/tforce/today'
    | '/api/integrations/daily-changes'
    | '/api/integrations/extra-job-drafts'
    | '/api/integrations/imports'
    | '/api/integrations/messages'
    | '/api/integrations/morning-list'
    | '/extra-jobs/'
    | '/hovership/'
    | '/payroll/'
    | '/hovership/week/$weekId'
    | '/tforce/week/$weekId'
    | '/tforce/week/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/drivers'
    | '/exceptions'
    | '/services'
    | '/settlements'
    | '/styleguide'
    | '/week'
    | '/auth/callback'
    | '/auth/dev'
    | '/auth/login'
    | '/auth/logout'
    | '/payroll-export/$runId'
    | '/'
    | '/extra-jobs/new'
    | '/payroll/$runId'
    | '/settings/audit'
    | '/settings/rates'
    | '/settings/team'
    | '/tforce/today'
    | '/api/integrations/daily-changes'
    | '/api/integrations/extra-job-drafts'
    | '/api/integrations/imports'
    | '/api/integrations/messages'
    | '/api/integrations/morning-list'
    | '/extra-jobs'
    | '/hovership'
    | '/payroll'
    | '/hovership/week/$weekId'
    | '/tforce/week/$weekId'
    | '/tforce/week'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/drivers'
    | '/_app/exceptions'
    | '/_app/services'
    | '/_app/settlements'
    | '/_app/styleguide'
    | '/_app/week'
    | '/auth/callback'
    | '/auth/dev'
    | '/auth/login'
    | '/auth/logout'
    | '/payroll-export/$runId'
    | '/_app/'
    | '/_app/extra-jobs/new'
    | '/_app/payroll/$runId'
    | '/_app/settings/audit'
    | '/_app/settings/rates'
    | '/_app/settings/team'
    | '/_app/tforce/today'
    | '/api/integrations/daily-changes'
    | '/api/integrations/extra-job-drafts'
    | '/api/integrations/imports'
    | '/api/integrations/messages'
    | '/api/integrations/morning-list'
    | '/_app/extra-jobs/'
    | '/_app/hovership/'
    | '/_app/payroll/'
    | '/_app/hovership/week/$weekId'
    | '/_app/tforce/week/$weekId'
    | '/_app/tforce/week/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthDevRoute: typeof AuthDevRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  PayrollExportRunIdRoute: typeof PayrollExportRunIdRoute
  ApiIntegrationsDailyChangesRoute: typeof ApiIntegrationsDailyChangesRoute
  ApiIntegrationsExtraJobDraftsRoute: typeof ApiIntegrationsExtraJobDraftsRoute
  ApiIntegrationsImportsRoute: typeof ApiIntegrationsImportsRoute
  ApiIntegrationsMessagesRoute: typeof ApiIntegrationsMessagesRoute
  ApiIntegrationsMorningListRoute: typeof ApiIntegrationsMorningListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exceptions': {
      id: '/_app/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof AppExceptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settlements': {
      id: '/_app/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof AppSettlementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/styleguide': {
      id: '/_app/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof AppStyleguideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week': {
      id: '/_app/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AppWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dev': {
      id: '/auth/dev'
      path: '/auth/dev'
      fullPath: '/auth/dev'
      preLoaderRoute: typeof AuthDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-export/$runId': {
      id: '/payroll-export/$runId'
      path: '/payroll-export/$runId'
      fullPath: '/payroll-export/$runId'
      preLoaderRoute: typeof PayrollExportRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/extra-jobs/': {
      id: '/_app/extra-jobs/'
      path: '/extra-jobs'
      fullPath: '/extra-jobs/'
      preLoaderRoute: typeof AppExtraJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extra-jobs/new': {
      id: '/_app/extra-jobs/new'
      path: '/extra-jobs/new'
      fullPath: '/extra-jobs/new'
      preLoaderRoute: typeof AppExtraJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hovership/': {
      id: '/_app/hovership/'
      path: '/hovership'
      fullPath: '/hovership/'
      preLoaderRoute: typeof AppHovershipIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/$runId': {
      id: '/_app/payroll/$runId'
      path: '/payroll/$runId'
      fullPath: '/payroll/$runId'
      preLoaderRoute: typeof AppPayrollRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/rates': {
      id: '/_app/settings/rates'
      path: '/settings/rates'
      fullPath: '/settings/rates'
      preLoaderRoute: typeof AppSettingsRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tforce/today': {
      id: '/_app/tforce/today'
      path: '/tforce/today'
      fullPath: '/tforce/today'
      preLoaderRoute: typeof AppTforceTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/integrations/daily-changes': {
      id: '/api/integrations/daily-changes'
      path: '/api/integrations/daily-changes'
      fullPath: '/api/integrations/daily-changes'
      preLoaderRoute: typeof ApiIntegrationsDailyChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/extra-job-drafts': {
      id: '/api/integrations/extra-job-drafts'
      path: '/api/integrations/extra-job-drafts'
      fullPath: '/api/integrations/extra-job-drafts'
      preLoaderRoute: typeof ApiIntegrationsExtraJobDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/imports': {
      id: '/api/integrations/imports'
      path: '/api/integrations/imports'
      fullPath: '/api/integrations/imports'
      preLoaderRoute: typeof ApiIntegrationsImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/messages': {
      id: '/api/integrations/messages'
      path: '/api/integrations/messages'
      fullPath: '/api/integrations/messages'
      preLoaderRoute: typeof ApiIntegrationsMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/morning-list': {
      id: '/api/integrations/morning-list'
      path: '/api/integrations/morning-list'
      fullPath: '/api/integrations/morning-list'
      preLoaderRoute: typeof ApiIntegrationsMorningListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/hovership/week/$weekId': {
      id: '/_app/hovership/week/$weekId'
      path: '/hovership/week/$weekId'
      fullPath: '/hovership/week/$weekId'
      preLoaderRoute: typeof AppHovershipWeekWeekIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tforce/week/': {
      id: '/_app/tforce/week/'
      path: '/tforce/week'
      fullPath: '/tforce/week/'
      preLoaderRoute: typeof AppTforceWeekIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tforce/week/$weekId': {
      id: '/_app/tforce/week/$weekId'
      path: '/tforce/week/$weekId'
      fullPath: '/tforce/week/$weekId'
      preLoaderRoute: typeof AppTforceWeekWeekIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDriversRoute: typeof AppDriversRoute
  AppExceptionsRoute: typeof AppExceptionsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettlementsRoute: typeof AppSettlementsRoute
  AppStyleguideRoute: typeof AppStyleguideRoute
  AppWeekRoute: typeof AppWeekRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExtraJobsNewRoute: typeof AppExtraJobsNewRoute
  AppPayrollRunIdRoute: typeof AppPayrollRunIdRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsRatesRoute: typeof AppSettingsRatesRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppTforceTodayRoute: typeof AppTforceTodayRoute
  AppExtraJobsIndexRoute: typeof AppExtraJobsIndexRoute
  AppHovershipIndexRoute: typeof AppHovershipIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppHovershipWeekWeekIdRoute: typeof AppHovershipWeekWeekIdRoute
  AppTforceWeekWeekIdRoute: typeof AppTforceWeekWeekIdRoute
  AppTforceWeekIndexRoute: typeof AppTforceWeekIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDriversRoute: AppDriversRoute,
  AppExceptionsRoute: AppExceptionsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettlementsRoute: AppSettlementsRoute,
  AppStyleguideRoute: AppStyleguideRoute,
  AppWeekRoute: AppWeekRoute,
  AppIndexRoute: AppIndexRoute,
  AppExtraJobsNewRoute: AppExtraJobsNewRoute,
  AppPayrollRunIdRoute: AppPayrollRunIdRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsRatesRoute: AppSettingsRatesRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppTforceTodayRoute: AppTforceTodayRoute,
  AppExtraJobsIndexRoute: AppExtraJobsIndexRoute,
  AppHovershipIndexRoute: AppHovershipIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppHovershipWeekWeekIdRoute: AppHovershipWeekWeekIdRoute,
  AppTforceWeekWeekIdRoute: AppTforceWeekWeekIdRoute,
  AppTforceWeekIndexRoute: AppTforceWeekIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDevRoute: AuthDevRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  PayrollExportRunIdRoute: PayrollExportRunIdRoute,
  ApiIntegrationsDailyChangesRoute: ApiIntegrationsDailyChangesRoute,
  ApiIntegrationsExtraJobDraftsRoute: ApiIntegrationsExtraJobDraftsRoute,
  ApiIntegrationsImportsRoute: ApiIntegrationsImportsRoute,
  ApiIntegrationsMessagesRoute: ApiIntegrationsMessagesRoute,
  ApiIntegrationsMorningListRoute: ApiIntegrationsMorningListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
