import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { dailyChangesOutput, extraJobOutput } from '~/server/integrations';

const dir = new URL('../../n8n/workflows/', import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith('.json') && !f.endsWith('.schema.json'));
type Wf = { name: string; nodes: { name: string; type: string; parameters: { url?: string } }[]; connections: Record<string, { main: { node: string }[][] }> };

describe('n8n workflows (generated by scripts/build-n8n.mjs)', () => {
  it('has the four flows from docs/integrations.md', () => {
    expect(files.sort()).toEqual(['morning-list.json', 'reminders.json', 'report-ingest.json', 'whatsapp-inbound.json']);
  });

  for (const f of files) {
    const wf = JSON.parse(readFileSync(new URL(f, dir), 'utf8')) as Wf;
    it(`${f}: every connection points at a node that exists`, () => {
      const names = new Set(wf.nodes.map((n) => n.name));
      expect(names.size).toBe(wf.nodes.length);
      for (const [from, c] of Object.entries(wf.connections)) {
        expect(names.has(from), from).toBe(true);
        for (const out of c.main) for (const to of out) expect(names.has(to.node), `${from} -> ${to.node}`).toBe(true);
      }
    });
    it(`${f}: portal calls only use integration endpoints that exist`, () => {
      for (const n of wf.nodes) {
        const m = /\/api\/integrations(\/[\w-]+)/.exec(n.parameters.url ?? '');
        if (m) expect(existsSync(new URL(`../../src/routes/api/integrations${m[1]}.ts`, import.meta.url)), m[1]).toBe(true);
      }
    });
  }

  it('what the AI schema allows passes the portal validation', () => {
    const daily = { confirm_all: false, changes: [{ route: '9000E', driver_name: 'Norwin Saloman', matched_driver_id: '00000000-0000-4000-8000-000000000001', matched_contractor_id: null, contractor_hint: null, confidence: 0.94 }] };
    const job = { service: 'recovery_route', date: '2026-06-18', near_route: '9000R', driver_id: null, contractor_id: '00000000-0000-4000-8000-000000000002', payee_name: 'Puma', client_amount: 180, driver_amount: 120, order_number: 'TF-55821', note: null, missing: [] };
    expect(dailyChangesOutput.safeParse(daily).success).toBe(true);
    expect(extraJobOutput.safeParse(job).success).toBe(true);
    const schema = JSON.parse(readFileSync(new URL('ai-output.schema.json', dir), 'utf8'));
    const dailyKeys = schema.properties.daily_changes.anyOf[1].properties.changes.items.required;
    const jobKeys = schema.properties.extra_job.anyOf[1].required;
    for (const k of dailyKeys) expect(Object.keys(dailyChangesOutput.shape.changes.unwrap().element.shape)).toContain(k);
    for (const k of jobKeys) expect(Object.keys(extraJobOutput.shape)).toContain(k);
  });
});
